### ISSUE TITLE
licensing? unsigned binaries? end-user's perspective

### ISSUE THREAD

**Issue by borkd** [gilbertchen/duplicacy-cli#10]
If usability claims made in README.md are true duplicacy has a potential to become a valued part of sysadmin's toolbox. As of this writing there are some wrinkles though, which could and should be explicitly addressed:

### Licensing model?
What are the intentions here? 

### Opening the sources / code review key for broad(er) adoption.
- Case 1 - Duplicacy is the best thing since sliced bread. Still, bugs happen. Test suite could always be expanded for weird corner cases.. 

- Case 2 - Ability to restore data from one's backups after a day, month or 10 years is rather essential. Duplicacy backup sitting in S3 or Glacier is now the last and only remaining source of precious data after a few years of seamless backups and restores. You have run into an issue that didn't manifest itself before and are now out of ideas. Original sole author/organization supporting it is now MIA and you can't troubleshoot on your own. Was using cloud backend with duplicacy this the best use of your money and time?

- Case 3 - Not insinuating anythint, just playing Devil's Advocate: What lurks in the unsigned binaries? How do I know the binary is published by someone with an established web of trust and not by nefarious entity patiently waiting to trigger a ransomware attack at some later date?

### Backups need to be boring.
Regardless if you plan to back up megabytes or petabytes. Playing with unsigned binaries on dummy data and getting excited by cool features is one thing, using them on valuable data and hoping for the best is another (anything worth backing up is valuable, right?). This becomes especially true when one has also been footing the bill for remote cloud storage and associated I/O requests for the lifetime of backed up data.

**Comment by gilbertchen** [comment]
I completely agree that opening the source is crucial to the success of Duplicacy.  However, I don't think main-stream open source licenses like GPL, MIT, or BSD would work well for me in terms of sustainability at this early stage and without external funding.  An "open-source" licensing model that allows for free personal use but imposes limits on commercial uses is what I'm currently looking at, for instance, something similar to [Unity](https://unity3d.com/legal/eula).

I would like to hear your opinions (and everyone else's reading this thread) towards such a licensing model.

**Comment by bbinet** [comment]
I think that being able to check the source code is a very important feature of a backup tool because our data always matter the most!
So I also think that opening the source is crucial to the success of Duplicacy so that users can be confident about potential security issues or data safety issues.
