### ISSUE TITLE
Specify SFTP port?

### ISSUE THREAD

**Issue by cron410** [gilbertchen/duplicacy-cli#16]
Currently it seems SFTP port is hardcoded to 22. Not all SFTP servers are listening on port 22. 

Error I get:
$ duplicacy_win_x64_0.1.10.exe init repo sftp://my.domain.org:5525/path/to/repository
Failed to load the SFTP storage at sftp://my.domain.org:7000/path/to/repository: 
dial tcp: too many colons in address my.domain.org:7000:22

**Comment by gilbertchen** [comment]
Version 1.1 should support this.

**Comment by gilbertchen** [comment]
Fixed in release 1.0.1
