### ISSUE TITLE
Connecting to SFTP

### ISSUE THREAD

**Issue by cron410** [gilbertchen/duplicacy-cli#17]
First off, let me preface this by saying Filezilla works fine.

Since I have static IP addresses at both locations, I forwarded port 22 from the WAN to the NAS that hosts OpenSSH for SFTP, but only the public IP of the location where Duplicacy is being used is allowed to connect on port 22. 

No matter what I do, Duplicacy will not connect. Duplicacy from the command line gives me: 
`ssh: handshake failed: EOF`

Windows GUI gives me:

`Duplicacy Error`

`ERROR Failed to load the SFTP storage at sftp://duplicacy@my.domain.com/VMBACKUPS: Can't access the storage path VMBACKUPS: file does not exist`

**Comment by gilbertchen** [comment]
The error reported by the GUI version actually showed that the ssh connection was good; it just couldn't find the dir VMBACKUPS.  Since the GUI version is merely a wrapper of the CLI version, this makes me believe that it could be a temporary network issue.

**Comment by cron410** [comment]
Both PuTTY and Filezilla are operating correctly with the same SSH server
on port 22. Your SFTP implementation is supposed to work over the internet
right? Not just locally?

**Comment by gilbertchen** [comment]
Did you keep getting the handshake error with the CLI version?

**Comment by cron410** [comment]
Sorry for the delay. I just tried by IP address and it still fails. If I set the target as a nonexistent IP or domain, it gives different errors.

```
C:\Users\hive\AppData\Local\Duplicacy>duplicacy_win_x64_0.1.11.exe init server_backup ftp://ip.address/share/keg/backups/devices/pitt2012/

Failed to load the SFTP storage at sftp://ip.address/share/keg/backups/devices/pitt2012/: ssh: handshake failed: EOF
```

**Comment by gilbertchen** [comment]
We use https://github.com/pkg/sftp for the SFTP storage.

I tested the sftp connection on Windows to a linux host over the internet with an added latency of up to 1000ms and it still worked.

**Comment by cron410** [comment]
I was able to get it to log in with the GUI, but it states there is no such file when I know for a fact the path is correct. I even copied it from Filezilla. I removed the preceeding slash so the command shown during the init doesnt have mydomain.com:22//path/to/file and now has mydomain.com:22/path/to/file. The path doesn't work with or without the trailing slash so who knows what is going on there. I now have 3 different linux servers to try with, all on the internet, all running different recent versions of OpenSSH and Dropbear. Duplicacy cannot find "the file" on any of them.

I still don't quite understand how to specify username and password from command line. I've tried the set and init commands and nothing seems to work right. I think you need to make some kind of tutorial to get the basics down. Your user guide is too broad and provides no real command examples.

**Comment by gilbertchen** [comment]
The sftp storage doesn't support customized ports yet, so you need to remove ':22'.  If there is double slash after the host name (mydomain.com//path/to/file), then it is an absolute path starting from the root directory, otherwise it is a relative path starting from the home directory.

The username is specified in the storage url, like sftp://user@mydomain.com/path/to/file.  Duplicacy will then ask for the password from the command line.

**Comment by gilbertchen** [comment]
Starting from version 1.0.1, customized sftp ports are now supported.
