### ISSUE TITLE
Q: support for road warriors?

### ISSUE THREAD

**Issue by FredThompsonII** [gilbertchen/duplicacy-cli#21]
The best way to illustrate this question is with a scenario:

1) baseline: My wife and I have identical filesets on portable computers.
2) She modifies a local copy of a file.
3) I modify a local copy of the same file in a different manner.

At this point, both of our local copies are valid but we don't know about the modifications made by the other party.

4) I sync the master fileset with duplicacy.

What happens when she syncs?

**Comment by gilbertchen** [comment]
Duplicacy is not a file sync tool.  You and your wife will likely work on different repositories (each with a unique repository id), so the changes you make will still be independent of each other and not known to the other.  If the modified files share a common chunk only one copy of that chunk will be saved in the storage.
