### ISSUE TITLE
Include/exclude file patterns

### ISSUE THREAD

**Issue by jlesage** [gilbertchen/duplicacy-cli#22]
It seems that the [Exclude/include file patterns](https://github.com/gilbertchen/duplicacy-beta/blob/master/GUIDE.md#includeexclude-patterns) documentation needs some updates.

* The include mark is '+', while the exclude one is '-'.  This is reversed in the documentation.
* Documentation should mention that there is no space after the mark.
* Adding an example of a `filter` file would be useful.

I found that when you want to include a file, all the directories between the repository and the file need to be added.  For example, if the repository is at `/` and I want to include the file `/var/lib/app/myfile`, I need to use the following includes:
```
+var/
+var/lib/
+var/lib/app/
+var/lib/app/myfile
```

I was expecting that adding `+var/lib/app/myfile` would be enough.

Finally, it would be nice to be able to include files that are outside the repository.  In my case, I need to backup multiple files/directories, for which the common folder is the root one (`/`).  I would like to put the repository elsewhere.

**Comment by gilbertchen** [comment]
The documentation certainly needs some updates.

Duplicacy treats the first-level symlinks differently.  For these symlinks that point to other directories it will scan those directories.  It will not try to follow the symlinks that are not the first-level ones.  So if you want to include directories outside the repository, just create symlinks to them right under the repository root.

**Comment by jlesage** [comment]
Thanks for the tip, this should definitely be documented!
