### ISSUE TITLE
Restore from storage without knowing snapshot id

### ISSUE THREAD

**Issue by nrudnik** [gilbertchen/duplicacy-cli#23]
It does not appear possible to create a new repository from scratch and link it to a previously created repository residing on remote storage without knowing the snapshot id used by the the former repository.

For example, if the local repository is completely lost and you want to recover by restoring from the remote storage, you might want to inspect the remote storage to see which snapshot IDs are available. There seems to be no way to find what exists on the remote storage independent of a properly initialized local repository. However, if you know the snapshot id you want, you can init a new local repository with the proper snapshot id and find the snapshot to begin restore of the desired revision. It would be nice to not have to remember the correct snapshot ID to be able to recover from a catastrophic event.

**Comment by gilbertchen** [comment]
If you look under the _snapshot_ directory on the storage, you will find all snapshot IDs that are used as the names of the directories to store snapshot files.  For instance, if the snapshot ID of your local repository is _repository1_, then there'll be a directory named _snapshots/repository1_ on the storage.

**Comment by nrudnik** [comment]
Thanks, that's what I was looking for.
