### ISSUE TITLE
Multiple 'chunks' folders present in Google Drive remote storage

### ISSUE THREAD

**Issue by thrnz** [gilbertchen/duplicacy-cli#26]
When I first initialized the remote storage, there were 3 folders present (chunks, fossils and snapshots). There is now an extra 256 empty 'chunks' folders, named 'chunks/00', 'chunks/01', ..... 'chunks/fe', 'chunks/ff'.

Google Drive screenshot: https://imgur.com/11W3DWI

Is this intended behavior, or has something gone wrong somewhere? I believe they appeared after adding a second repository - the CLI was reporting 'Listing Chunks' or something similar at the time they appeared - I could be wrong though. I should be able to reproduce and be more specific if this behavior isn't intended.

Using 1.1.3 CLI version on Windows 10 x64.

*edit* I can reproduce this simply by running a 'check'. The folders appear when the CLI reports 'Listing all chunks'.

**Comment by gilbertchen** [comment]
This is a bug.  These directories are designed for storages that impose some limit on the number of files each directory can have.  Since Google Drive does not have such a limit, these directories should not be created.

I'll fix this in the next update.

**Comment by thrnz** [comment]
Thanks. I've only just started trying out the software, but am so far pretty impressed with what I've seen so far.

**Comment by gilbertchen** [comment]
Fixed in release 1.1.4
