### ISSUE TITLE
Heavy Class C API use for B2

### ISSUE THREAD

**Issue by chaseadam** [gilbertchen/duplicacy-cli#30]
2500 calls allowed per day (for free) otherwise "B2 cap exceeded" (or raise your cap)

Transactions Class C
Cost: The first 2,500 of these calls are free each day, then
b2_authorize_account
$0.004 per 1,000
b2_create_bucket
$0.004 per 1,000
b2_list_buckets
$0.004 per 1,000
b2_list_file_names
$0.004 per 1,000
b2_list_file_versions
$0.004 per 1,000
b2_update_bucket
$0.004 per 1,000
b2_list_parts
$0.004 per 1,000
b2_list_unfinished_large_files
$0.004 per 1,000
b2_get_download_authorization
$0.004 per 1,000

**Comment by gilbertchen** [comment]
For each new chunk to be uploaded, b2_list_file_names must be called to make sure that the same chunk file doesn't already exist.  The default chunk size is 4M, so every day you can upload approximately 10G for free.  After that it will be $0.004 per 4GB, one time only, so it is still significantly lower than the storage fee.

Of course you can increase the default chunk size but that would reduce the level of deduplication.

**Comment by tbain98** [comment]
Wouldn't calling `b2_get_file_info` instead be both cheaper (priced at $0.004 per 10,000 instead of per 1,000) and more efficient (guaranteed to require only one round trip instead of `CEILING(N/1000)` where N is the number of chunks currently stored, plus it's possible that B2 will be able to return the answer faster)?

**Comment by gilbertchen** [comment]
The input parameter of `b2_get_file_info` is the file id, not the file path.  To get the file id you'll have to call other apis.  Therefore this call alone can't be used to determine if a chunk exists.

**Comment by tbain98** [comment]
Clearly I didn't look at that API call as carefully as I should have; thanks for the clarification.
