### ISSUE TITLE
Different repositories at common root with different filters

### ISSUE THREAD

**Issue by martinpengellyphillips** [gilbertchen/duplicacy-cli#33]
Just exploring the system and would like guidance on preferred way to handle having different backup sets (repositories?) with a common root and different filters?

For example: If I want to have two backup sets for personal media and general media I imagine I should initialise two repositories. However, as they would both have the same root (say `C:\Users\martin\media`) how do I then specify different include paths for each as I understand from the documentation that there can only be one `.duplicacy/filters` file.

So I'd like to achieve the following:

general-media
+C:\Users\martin\media\film
+C:\Users\martin\media\music

personal-media
+C:\Users\martin\media\photo
+C:\Users\martin\media\video

**Comment by gilbertchen** [comment]
The filters work on the file path relative to the repository, so '+music/*mp3' will include all mp3 files under the music subdirectory but not others.  So I think you can just start each include/exclude pattern with the subdirectory that each pattern applies to.

**Comment by martinpengellyphillips** [comment]
Hmmm, looking into this more I see that my question should be slightly different. 

How do you handle different backup sets that happen to share a common root?

To clarify, I want to be able to run two separate backups, one called 'personal-media' and one called 'general-media'. This is because I have different backup requirements for the two sets (frequency, storage etc).

So if the filesystem tree is:
```
C:
 |- Users
      |- martin
            |- media
                 |- film
                 |- music
                 |- photo
                 |- video
 ```

I'd want to backup `film` and `music` as one backup set "general-media" with `photo` and `video` backed up as a separate set "personal-media". 

However, this would mean initialising two repositories at `C:\Users\martin\media` which doesn't seem possible at present.

So what is recommended way to handle this setup or is it not supported at all?

**Comment by gilbertchen** [comment]
You can create two directories under media, and then create symlinks that point to the directories you want to back up.

For instance, media/general can have two symlinks, one pointing to c:\Users\martin\media\film and the other c:\Users\martin\media\music. You can then initialize media/general as a repository.

Duplicacy treats top-level symlinks differently -- if they point to absolute paths it will follow them as if they were sub-directories.  For symlinks that are not in the top-level or point to relative paths, Duplicacy will back up them as symlinks.

**Comment by martinpengellyphillips** [comment]
Aha. That makes sense - thanks.
