### ISSUE TITLE
Choose file at restore

### ISSUE THREAD

**Issue by jos3k4** [gilbertchen/duplicacy-cli#36]
Hi gilbertchen,

First of all, I've been testing this application with B2 storage and it works fine, but I currently have the option **no_save_password** to false but it didn't save the account-id/key, It request b2 credentials per instruction that I execute.

In addition, I have a suggestion that I think that could be useful for all the users, restore a single file from a given snapshot on the desired destination.

**Comment by gilbertchen** [comment]
The doc may be a bit confusing, but the **no_save_password** option is to disable the auto-saving of credentials.  Auto-saving of credentials is only available on Windows and macOS. If you run duplicacy on Linux and you don't have gnome-keyring set up, then you'll have to enter the account-id/key every time, regardless of what value **no_save_password** is.

You can store select files from a given snapshot, by specifying include patterns when you run the `restore` command.  If you want to restore a single file, the pattern is simply the path of the file relative to the repository (for instance, `dir1\dir2\file`)

**Comment by gilbertchen** [comment]
Alternatively, you can save credentials in environment variables to avoid entering them every time.  See [this table](https://github.com/gilbertchen/duplicacy-cli/blob/master/GUIDE.md#managing-passwords) for the names of environment variables that duplicacy will read from before asking for password input.
