### ISSUE TITLE
Question: Shadow volume and concurrent runs

### ISSUE THREAD

**Issue by martinpengellyphillips** [gilbertchen/duplicacy-cli#37]
On Windows 10 with `-vss` flag: If I run duplicacy concurrently to two different storages for the same repo I notice that when the one process exits faster (as writing to local storage) it logs that it deletes the shadow volume in use. 

Is this an issue? Would it cause a problem for the other process running or are the shadow volumes distinct per run?

**Comment by gilbertchen** [comment]
This only affects multiple duplicacy processes running on the same repository.  It doesn't affect processed running on different repositories.

The reason for this behavior is that golang doesn't recognize shadow volume paths (which starts with \\?\GLOBALROOT), so duplicacy has to create a symbolic link named `shadow` under the `.duplicacy` directory, leading to a conflict when multiple duplicacy processes are running on the same repository.

**Comment by martinpengellyphillips** [comment]
Ok - good to know I should avoid this when scheduling backups. Thanks!
