### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by marquis-de-muesli** [gilbertchen/duplicacy-cli#43]
I have recently had some trouble setting up a filter.
Basically i was trying to backup some specific folders, but exclude some subfolders within those

-foo/bar/
+foo/
-*

That however didnt back up anything at all within foo.
Eventually i found a working solution using 

-foo/bar/
+foo/*
-*

However based on the documentation it seems to me my first example should have worked as well?
Same behaviour on Windows and Linux version.

**Comment by gilbertchen** [comment]
The documentation isn't clear -- patterns ending with / only apply to directories, so +foo/ means the foo directory is included but any file under it is excluded by -*.  +foo/* apply to both directories and files.

I'lll fix the documentation.
