### ISSUE TITLE
Amazon Cloud Drive support?

### ISSUE THREAD

**Issue by abossard** [gilbertchen/duplicacy-cli#5]
Please :-)

**Comment by segator** [comment]
I can help with this implementation if the code is open.

**Comment by mike503** [comment]
+1 for sure. I would definitely use this if an ACD backend was avaialble, because of the encryption not just of file contents but filenames (and sizes) too.

**Comment by gilbertchen** [comment]
Ok, this will be the next storage to add after I'm done with the GUI version.

**Comment by gilbertchen** [comment]
The Amazon Cloud Drive just rejected our request to develop an ACD/Duplicacy integration:

```
Thank you for your interest in using the Amazon Drive developer tools. We consider a variety of factors as we evaluate each invite request, including the use case your application will support. While our goal is to offer a broad and compelling assortment of applications to Amazon Drive customers, we are currently unable to approve your request for access.
```

So I think this will not happen in the near future.

**Comment by ywLBhGk2noZLbY7** [comment]
While I understand the business model, this is really putting me off ACD. Many projects I'd like to see utilizing it (Including yours) are being rejected, meaning "as long as you're not planning on storing a lot of data, it's unlimited".

**Comment by skydvr** [comment]
what about taking advantage of the acd_cli project as your "access" to acd?  The acd backend for duplicity utilizes this and it works well.
