### ISSUE TITLE
S3 on Linux can't login

### ISSUE THREAD

**Issue by noizo** [gilbertchen/duplicacy-cli#51]
`duplicacy init postgres_s3 s3://oregon@postgres-backup.s3.amazonaws.com/postgres-backup`

```
Enter S3 Access Key ID:KJCBWECJBNKEWJCN
Enter S3 Secret Access Key:lekrfnlLKNLNIHUO8KJNDCS89HNKJNLNlkn
Failed to configure the storage: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

I'm 100% sure credentials are good.
I use them in s3cmd

Same on Mac btw.
![duplicacy trial edition 1 2 4 28expires in 29 days 29 2017-05-12 17-07-47](https://cloud.githubusercontent.com/assets/1682474/26004374/dbd865fe-3735-11e7-9f4d-e31ae9b063b8.png)

**Comment by gilbertchen** [comment]
The storage url should be (assuming the bucket name is postgres-backup):
```
s3://us-west-2@amazon.com/postgres-backup
```
You should immediately edit your post to remove your access key (if it is the real one), delete it in your s3 console and create a new one.   Some S3 key searching bots may have already grabbed your key.

**Comment by noizo** [comment]
I'll try. 
Key is fake

**Comment by noizo** [comment]
It was a region issue. Thanks
