### ISSUE TITLE
No compression level in 2.0

### ISSUE THREAD

**Issue by noizo** [gilbertchen/duplicacy-cli#53]
GUIDE.MD
![duplicacy-cli-guide md at master gilbertchen-duplicacy-cli 2017-05-17 11-23-09](https://cloud.githubusercontent.com/assets/1682474/26147947/6330fdf0-3af5-11e7-958d-6880a18d4818.png)

While Duplicacy 2.0.0 gives me that

```
NAME:
   duplicacy init - Initialize the storage if necessary and the current directory as the repository

USAGE:
   duplicacy init [command options] <snapshot id> <storage url>

OPTIONS:
   -encrypt, -e 		encrypt the storage with a password
   -chunk-size, -c 4M 		the average size of chunks
   -max-chunk-size, -max 16M 	the maximum size of chunks (defaults to chunk-size * 4)
   -min-chunk-size, -min 1M 	the minimum size of chunks (defaults to chunk-size / 4)
```

No compression for duplicacy?

**Comment by gilbertchen** [comment]
Starting from version 1.2.0 we switched from zlib to lz4 for the default compression algorithm.  lz4 is so much faster than the zlib in our testing that it makes not sense to use zlib any more.  Therefore we removed the option to choose the compression level for the init command.

**Comment by noizo** [comment]
Understood. Thanks.
Maybe it's a good idea to update wiki? :)
