### ISSUE TITLE
Can you share a script to automate backups/checks/prunes?

### ISSUE THREAD

**Issue by ovizii** [gilbertchen/duplicacy-cli#9]
I am currently using borg and they provide a sample script which makes life a lot easier than having to cobble this together on your own:  https://borgbackup.readthedocs.org/en/stable/quickstart.html#automating-backups 

I'm looking to backup multiple LXCs to say S3 so I need to have a script that backs up, checks and prunes according to my needs and a way to safely store the access data for S3.

**Comment by gilbertchen** [comment]
A somewhat equivalent script would be:
```
#!/bin/sh
cd ~
duplicacy backup -stats
duplicacy prune -keep 0:180 -keep 7:28 -keep 1:7
```

Before running this script, however, you need to set up the repository (the directory to be backed up, which is your home directory in this case).  This command gets the repository ready:

```
cd ~
duplicacy init <snapshot id> s3://amazon.com/bucket/path
```

To exclude/include files and directory, you can edit ~/.duplicacy/filters and add patterns.

**Comment by ovizii** [comment]
Thanks, would you mind explaining in some more detail how to i.e. back something up from the Linux command line? I read your docu and it mentions  gnome-keyring but I'm talking about a server I don't usually install anything gnome or KDe related. 

Back in the duply/duplicity days, I could save the whole config in a file and only allow the user who was doing the backup access and that was it.

Any pointers would be welcome.
